import { useEffect, useState } from 'react';
import { getSession, queueExpense, request } from '../lib/api';
export default function Expenses(){
 const role=getSession()?.user?.role; const [items,setItems]=useState([]); const [form,setForm]=useState({title:'',amount:'',currency:'TOMAN',note:''}); const [msg,setMsg]=useState('');
 async function load(){ if(role==='employee')return; try{setItems(await request('/api/expenses'))}catch{} }
 useEffect(()=>{load()},[]);
 async function submit(e){e.preventDefault();setMsg(''); const payload={...form,amount:Number(form.amount)}; try{await request('/api/expenses',{method:'POST',body:JSON.stringify(payload)});setMsg('هزینه ثبت شد.');load()}catch{const n=queueExpense(payload);setMsg(`اینترنت/سرور در دسترس نبود؛ هزینه آفلاین ذخیره شد (${n} مورد منتظر ارسال).`)} setForm({title:'',amount:'',currency:'TOMAN',note:''});}
 async function decision(id,d){await request(`/api/expenses/${id}/decision`,{method:'POST',body:JSON.stringify({decision:d})});load()}
 return <section><div className="section-head"><div><h2>هزینه‌ها</h2><p>عنوان هزینه آزاد است؛ دلار و تومان مستقل ثبت می‌شوند.</p></div></div><div className="panel"><form className="grid-form" onSubmit={submit}><label>عنوان هزینه<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>مبلغ<input required type="number" min="0" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>واحد<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option value="TOMAN">تومان</option><option value="USD">دلار</option></select></label><label className="wide">توضیحات<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><button>ثبت هزینه</button></form>{msg&&<div className="notice">{msg}</div>}</div>{role!=='employee'&&<div className="panel"><table><thead><tr><th>شرح</th><th>مبلغ</th><th>وضعیت</th><th>ثبت‌کننده</th><th>عملیات</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.title}</td><td>{Number(x.amount).toLocaleString()} {x.currency==='USD'?'$':'تومان'}</td><td><span className={`status ${x.status}`}>{x.status==='pending'?'منتظر':x.status==='approved'?'تأیید':'رد'}</span></td><td>{x.created_by_name}</td><td>{x.status==='pending'&&<div className="actions"><button onClick={()=>decision(x.id,'approved')}>تأیید</button><button className="ghost danger" onClick={()=>decision(x.id,'rejected')}>رد</button></div>}</td></tr>)}</tbody></table></div>}</section>
}
